# Generated by Django 2.0.4 on 2018-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlam', '0002_auto_20180421_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=None),
        ),
    ]
