# Generated by Django 2.0.4 on 2018-04-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlam', '0003_users_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nickname',
        ),
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='users',
            name='type_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
